### ISSUE TITLE
Getting No suitable driver found for jdbc:neo4j://localhost:7474/

### ISSUE THREAD

**Issue by jpalbuja** [neo4j-documentation/developer-resources#36]
Hi, I am trying to just use the jdbc driver and I am getting No suitable driver found for jdbc:neo4j://localhost:7474/ with Neo 2.1.4

**Comment by ravenAtSafe** [comment]
That implies that your Neo4j JDBC driver is not in your Java classpath

**Comment by jexp** [comment]
And make sure you get the full jar, with dependencies: http://m2.neo4j.org/content/repositories/releases/org/neo4j/neo4j-jdbc/2.1.4/

**Comment by LSamanth** [comment]
I'm getting  No suitable driver found for jdbc:neo4j://localhost:7474/ with neo4j 2.1.6 . I'm using 
neo4j-jdbc-2.1.4-jar-with-dependencies.jar .

**Comment by jexp** [comment]
Can you share your full code or a failing test?

**Comment by LSamanth** [comment]
```
Feb 11, 2015 4:05:03 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet mvc-dispatcher threw exception
java.sql.SQLException: No suitable driver found for jdbc:neo4j://localhost:7474/
    at java.sql.DriverManager.getConnection(DriverManager.java:596)
    at java.sql.DriverManager.getConnection(DriverManager.java:215)
    at com.aig.neo4jpoc.platform.JdbcCypherExecutor.<init>(JdbcCypherExecutor.java:19)
    at com.aig.neo4jpoc.platform.JdbcCypherExecutor.<init>(JdbcCypherExecutor.java:15)
    at com.aig.neo4jpoc.dao.Neo4jDAOImpl.createCypherExecutor(Neo4jDAOImpl.java:39)
    at com.aig.neo4jpoc.dao.Neo4jDAOImpl.search(Neo4jDAOImpl.java:78)
    at com.aig.neo4jpoc.controller.Neo4jController.search(Neo4jController.java:51)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:212)
    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:126)
    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:96)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:617)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:578)
    at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:80)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:900)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:827)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:778)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:861)
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:606)
    at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by jexp** [comment]
Your source code not your stacktrace !!!

**Comment by roopaml** [comment]
Could you please tell what is the version of neo4j-jdbc that is compatible with Java 6?
